# Generated by Django 5.0.1 on 2024-07-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesperson',
            unique_together={('first_name', 'last_name')},
        ),
    ]
